import type { Metadata } from "next";
import { Share_Tech_Mono, Space_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";
import ViewCanvas from "@/components/ViewCanvas";
import LenisScroll from "@/components/common/LenisScroll";

const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-space-mono",
  display: "swap",
});

const shareTechMono = Share_Tech_Mono({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-share-tech-mono",
  display: "swap"

})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${spaceMono.variable} ${shareTechMono.variable}`}>
      <body suppressHydrationWarning={false}>
        <div className="lenis-root">
          <div className="lenis-content">
            <LenisScroll />
            <Header />
            {children}
            <ViewCanvas />
          </div>
        </div>
      </body>
    </html>
  );
}
