import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/common/Header";
import ViewCanvas from "@/components/ViewCanvas";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <ViewCanvas/>
      </body>
    </html>
  );
}
