import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";
import ViewCanvas from "@/components/ViewCanvas";
import { SetupScrollSmoother } from "@/components/common/ScrollSmoother";

const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-space-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={spaceMono.variable}>
      <body className="overflow-x-hidden">
        <ViewCanvas />
        <div id="smooth-wrapper">
          <Header />
          <div id="smooth-content">
            <SetupScrollSmoother />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
