export const ATMOSPHERE_CONFIG = {
  STARS_INITIAL_OPACITY: 0,
  EMBERS_INITIAL_OPACITY: 1,

  GRIMOIRE_FADE_START: "top bottom",
  GRIMOIRE_FADE_END: "top top",

  SPARKS_FADE_DURATION: "+=600%",
  SPARKS_FADE_THRESHOLD: 0.95,

  STARS_MAX_OPACITY: 1,
  STARS_MID_OPACITY: 0.5,
  EMBERS_MIN_OPACITY: 0,

  CRAFTINGS_FADE_START: "bottom 50%",
  CRAFTINGS_FADE_END: "bottom top",
} as const;
